# ##############################################################################
# generateVersion.cmake
#
# CMake script invoked at BUILD time (via add_custom_target) to generate
# cErrorDriverVersion.h. Re-runs on every cmake --build invocation so the
# timestamp in PATCH is always current.
#
# Required inputs (passed via -D on the command line):
#   VERSION_MAJOR  — major version integer
#   VERSION_MINOR  — minor version integer
#   VERSION_PATCH  — patch version integer
#   VERSION_BUILD_TYPE     — "STATIC" or "DYNAMIC"
#   OUTPUT_FILE    — absolute path to write the generated header
# ##############################################################################

# Compute PATCH as YYMMDDHHMMSS (2-digit year, month, day, hour, minute, second)
string(TIMESTAMP BUILD_DATE_TIME "%y%m%d%H%M%S")
set(HEADER_CONTENT
"/* *************************************************************
 * cIntegrityDriverVersion.h
 * Auto-generated by CMake at build time. DO NOT EDIT MANUALLY.
 * Regenerated on every cmake --build invocation.
 * Version: ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_BUILD_TYPE}.${BUILD_DATE_TIME}.
 ***************************************************************/
#ifndef C_INTEGRITY_DRIVER_VERSION_H
#define C_INTEGRITY_DRIVER_VERSION_H

/* Major version — incremented on breaking API changes */
#define INTEGRITY_DRIVER_VERSION_MAJOR  ${VERSION_MAJOR}

/* Minor version — incremented on backward-compatible feature additions */
#define INTEGRITY_DRIVER_VERSION_MINOR  ${VERSION_MINOR}

/* Patch — incremented on backward-compatible feature additions */
#define INTEGRITY_DRIVER_VERSION_PATCH  ${VERSION_PATCH}

/* Build date/time — build timestamp encoded as YYMMDDHHMMSS */
#define INTEGRITY_DRIVER_VERSION_BUILD_DATE_TIME  ${BUILD_DATE_TIME}

/* Build type — STATIC or DYNAMIC */
#define INTEGRITY_DRIVER_VERSION_BUILD_TYPE  \"${VERSION_BUILD_TYPE}\"

#define INTEGRITY_DRIVER_VERSION_BUILD_TYPE_ENUM  ${VERSION_BUILD_TYPE_ENUM}


/* Composite version string: \"Major.Minor.YYMMDDHHMMSS.BuildType\"
 * Adjacent string-literal concatenation is resolved at compile time. */
#define INTEGRITY_DRIVER_VERSION_STRING  \\
    \"${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_BUILD_TYPE}.${BUILD_DATE_TIME}\"

#endif /* C_INTEGRITY_DRIVER_VERSION_H */
")

file(WRITE "${OUTPUT_FILE}" "${HEADER_CONTENT}")
message(STATUS "Generated ${OUTPUT_FILE}  [${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_BUILD_TYPE}.${BUILD_DATE_TIME}]")
